version: '2'

services:

  ipfs:
    image: ipfs/go-ipfs:v0.4.10
    expose:
      - "8080"
    ports:
      - "4001:4001"
      - "4002:4002/udp"
      - "8081"
    env_file:
      - frontend.env
    volumes:
      - ./data:/data/ipfs/
    networks:
      - frontend
    logging:
      driver: none

networks:
  frontend:
    external:
      name: nginx_default
